// <auto-generated />
namespace Shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addednew2columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednew2columns));
        
        string IMigrationMetadata.Id
        {
            get { return "202002190344252_Added new 2 columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
